### ISSUE TITLE
Calling $channel->exit_signal causes Win32 Perl to crash

### ISSUE THREAD

**Issue by jamessan** [rkitover/net-ssh2#15]
The simple script below (update with useful host & credentials) works fine when run from a Linux system but causes Perl to crash on Windows.  Getting rid of the call to exit_signal makes the crash go away.

```perl
use strict;
use warnings;
use Net::SSH2;

my $ssh = Net::SSH2->new();
$ssh->connect('host');
$ssh->auth_keyboard('username', 'password');
my $channel = $ssh->channel();
$channel->exec($ARGV[0]);
while (my $line = <$channel>) {
    print $line;
}
$channel->send_eof();
$channel->close();
$channel->wait_closed();

my $rc = $channel->exit_status();
print "Checking exit_signal\n";
my $sig = eval { $channel->exit_signal(); };
if ($@) {
    if ("$@" !~ m/libssh2 version 1.2.8/) {
        die $@;
    }
}
elsif ($sig) {
    print "Got exit_signal\n";
    $sig = eval "SIG$sig";
    $rc = $sig | 0x80;
}
print $rc;
```

**Comment by jamessan** [comment]
@salva Should d29af4678 also fix this?  Maybe we should put out a new version, or at least a dev version to get some CPAN testing.

**Comment by rkitover** [comment]
@jamessan @salva

Guys, you seem to have really picked up development on this module over the last couple of years, I was not really aware of this.

There are some things I would like to do as well, and I'd like to still be involved.

Can we all meet on freenode #libssh2 sometime? Salva can you arrange a time that is good for you?

Thanks.

Rafael

**Comment by salva** [comment]
>Guys, you seem to have really picked up development on this module over the last couple of years, I was not really aware of this.
>
>There are some things I would like to do as well, and I'd like to still be involved.
>
>Can we all meet on freenode #libssh2 sometime? Salva can you arrange a time that is good for you?



I think both of you are on the USA, right? Today at sometime in your morning would be a good time for me.

But anyway, my plan for this week is to be in front of the computer at almost any time, so, it should be easy to catch me there :-)

**Comment by salva** [comment]
@jamessan, regarding your question about the bug, the answer is:

I haven't tested it on Windows, but probably yes.

**Comment by salva** [comment]
this issue seems fixed and nobody has reported it again, so closing!

**Comment by jamessan** [comment]
I've confirmed that it was fixed.  Thanks!

**Comment by salva** [comment]
@jamessan, thanks for the feedback!
