### ISSUE TITLE
Using auth_agent method leaks file handles

### ISSUE THREAD

**Issue by neechbear** [rkitover/net-ssh2#22]
When authenticating against a host with the $ssh2->auth_agent($USERNAME) method, I note that the number of in-process open file handles increases by 1. From a cursory glance with a test script for debugging judicious use of `ss` and `lsof`, I've assumed that this extra file handle is a socket to the ssh-agent itself. All well and good and to be expected.

However, upon gracefully closing any open channels, and disconnecting the ssh object from the remote server, only the server socket connection appears to be closed, and the ssh-agent file handle remains open.

I have confirmed using `ss` and `netstat` that my test script does have the expected number of network connections open, but has twice the number of expected file handles open, which is in keeping with not closing the additional handle to the ssh-agent upon a disconnect.

I can provide the example test script I used to identify this problem if you wish.

**Comment by jamessan** [comment]
`libssh2_agent_free` gets called in the CLEANUP of auth_agent, so the connection to the agent should be cleaned up automatically.  What version of libssh2 are you using?  Are you sure this is an issue in Net-SSH2 and not in libssh2 itself?

**Comment by jamessan** [comment]
Hmm, but the generated SSH2.c doesn't have the call to `libssh2_agent_free`, so it seems that's the problem. :)

**Comment by jamessan** [comment]
Guess it would help if I were testing the current code.  Looks like @salva fixed this in a3b85d5b.  Can you confirm the latest code works for you, @neechbear?

**Comment by salva** [comment]
This issue is still happening.
