### ISSUE TITLE
test failure with 0.59_17

### ISSUE THREAD

**Issue by ferki** [rkitover/net-ssh2#34]
When running the test suite of current master (c8dd1e94203812eab30c7939b9990f958ba39266), I get the following failure:
```
#   Failed test 'channel close via tie interface'
#   at t/Net-SSH2.t line 436.
#          got: undef
#     expected: '1'
```
I'm just opening the issue quickly now so I don't forget about it, and I'm happy to provide more info details later.

**Comment by salva** [comment]
should be fixed now in 0.59_18!

**Comment by ferki** [comment]
I can confirm it passes with latest master (10a13884e27ce550bf93a5dd05e50edd637f190a), thank you!

**Comment by salva** [comment]
ok, thank you for reporting it!
