### ISSUE TITLE
auth() skips authentication via SSH agent

### ISSUE THREAD

**Issue by nfetisov** [rkitover/net-ssh2#35]
The check inside auth() for valid authentication methods in 0.59/0.60 
always skips auth_agent method: for auth_agent method name set as 'agent' in _auth_methods(), but corresponding method that could be 
supported by remote server is 'publickey'.

**Comment by salva** [comment]
Fixed in version 0.61: https://metacpan.org/release/SALVA/Net-SSH2-0.61
