### ISSUE TITLE
Can't build under Sierra

### ISSUE THREAD

**Issue by timarc** [rkitover/net-ssh2#38]
I have following issue.
I've install all required libraries with Homebrew for net::ssh2 compilation(openssl, libssh2), but can't build Net::SSH2 itself.

perl 5.18 default on Sierra.
```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

Looking for libraries...
Unable to find a working version of library ssh2 in the following directories: ...
```

**Comment by salva** [comment]
When the Makefile.PL detects it is running on a Mac, it unconditionally tries to install `openssl` and `libssh2` using `brew`, but it seems that recent versions of `brew` refuse to run as root for security reasons.

That's the reason for the `Error:...` messages in the OP. But those errors are harmless, the result codes from the `brew` calls are ignored.

@timarc, you should be able to use `Makefile.PL` `lib` and `inc` arguments to specify the location of the libssh2 files (where `brew` installed them), for instance:

`perl Makefile.PL lib=$HOME/libssh2/lib inc=$HOME/libssh2/include`

**Comment by timarc** [comment]
Hello

So it works well. Thank you very much for your help.

Regards,
Marc-@
