### ISSUE TITLE
Howto use -o option?

### ISSUE THREAD

**Issue by MarcusCaepio** [rkitover/net-ssh2#47]
Hi all, 
I am using https://metacpan.org/pod/Net::SSH2::Cisco to connect to a cisco device.
Unfortunately, I have to set the ssh option -oKexAlgorithms=+diffie-hellman-group1-sha1 on some host, but I cannot find a option whether in Net::SSH2 nor in Net::SS2::Cisco.
Can you tell me, how I have to define it?
Thanks in advance,
Marcus

**Comment by salva** [comment]
Net::SSH2 provides the method [method](https://metacpan.org/pod/Net::SSH2#method-(-type-[,-values...-]-)) for that.

I don't know how that feature can be accessed from Net::SSH2::Cisco though.

**Comment by MarcusCaepio** [comment]
Thanks salva. Seems there is no way to contact the maintainer of Net::SSH2::Cisco and he just did not implemented it

**Comment by salva** [comment]
`Net::SSH2::Cisco` has method `ssh` giving you access to the underlying `Net::SSH2` object. Something like the following should work:

    my $session = Net::SSH2::Cisco->new(host => ...);
    $nsc->ssh->method(...);
    $session->login('login', 'password');
