### ISSUE TITLE
Unable to install on macOS with openSSL@1.1

### ISSUE THREAD

**Issue by cdalvaro** [rkitover/net-ssh2#50]
Hi Salva,

I'm trying to install this module on macOS Catalina.

I have installed `openssl@1.1` via Homebrew, which is the only available formula for openssl right now on Homebrew, and I'm getting the following error:

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/carlos.alvaro/.cpanm/work/1584964163.39841/Net-SSH2-0.70/assertlibo3lG0CsK
  Reason: image not found
Unable to find a working version of library ssl in the following directories:
  /usr/local/lib
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
  /usr/lib
  /opt/perlbrew/perls/perl-5.24.4
  /usr
  /usr/local
  /opt
  /opt/local
  /usr/local/libssh2
  /opt/libssh2
  /usr/local/ssl
```

You can find attached to this issue the full log. 
[build.log](https://github.com/rkitover/net-ssh2/files/4369250/build.log)

Please, could you update the library dependency in order to use version `1.1` instead of `1.0`?

Thank you in advance.

**Comment by cdalvaro** [comment]
Indeed, OpenSSL 1.0 reached the EOL on 2019-12-31

Because that reason, Homebrew removed the OpenSSL 1.0 formula on PR https://github.com/Homebrew/homebrew-core/pull/46876

**Comment by rkitover** [comment]
I will take a look at MacOS installation issues.

**Comment by rkitover** [comment]
@cdalvaro can you please try this fix:

https://github.com/rkitover/net-ssh2/pull/51/commits/b63e005776196613a175c8764a2e6573eeecb563

**Comment by cdalvaro** [comment]
> @cdalvaro can you please try this fix:
> 
> [b63e005](https://github.com/rkitover/net-ssh2/commit/b63e005776196613a175c8764a2e6573eeecb563)

Nice! It works! 🎉
