### ISSUE TITLE
Broken link in HTML for https://metacpan.org/pod/Net::SSH2

### ISSUE THREAD

**Issue by roweber** [rkitover/net-ssh2#57]
In HTML line 2388, #Supported-key-formats ought to be #Key-formats ...
  <p>See also <a href="#Supported-key-formats">&quot;Supported key formats&quot;</a>.</p>

for consistency with HTML line 2636 
  <h2 id="Key-formats"><a id="Key"></a>Key formats</h2>

**Comment by salva** [comment]
Fixed in development version.
