### ISSUE TITLE
please clarify how exec() should be used

### ISSUE THREAD

**Issue by uperto** [rkitover/net-ssh2#6]
It seems other people found the documentation a bit light, according to cpanratings.

On this exact problem… After an exec() I looped on <$chan> and checked exit_status(), but sometimes the fetched output was truncated and the exit_code wrong (zero instead of non-zero). As i did not play with the blocking mode, which is on by default, i was expecting exec() not to return until the command is finished (enforcing blocking mode did not help either).

I found testing eof() was useless until the output was read, probably emptying an internal buffer then able to receive more data (and later EOF which is probably in-band).

So i end-up with the following working code:
       $channel->exec($command);

```
until ($channel->eof) {
    usleep(100);
    $self->{logger}->debug(sprintf("SSH command output: %s", trim($_))) while (<$channel>);
}

my $ret_code = $channel->exit_status;

$channel->close;
```

Please tell me if this is right and document it so other people can focus on more productive tasks.

**Comment by rkitover** [comment]
Non-blocking mode is kind of useless because we don't have any kind of event loop support right now, polling like you are doing is the only way.

However, in blocking mode, which is the default, channels work exactly as expected with no need for any of this.
