### ISSUE TITLE
How to get Net::SSH2 to use latest libssh2 v1.11.0 ciphers ?

### ISSUE THREAD

**Issue by lgastevens** [rkitover/net-ssh2#60]
Libssh2 v1.11.0 has become available a few days ago, and with it support of latest SSH ciphers, in particular rsa-sha2-512 and rsa-sha2-256, see https://github.com/libssh2/libssh2/issues/536

I have re-installed Net::SSH2 v0.73 using libssh2 v1.11.0, but it seems that Net::SSH2 is still reporting v1.8.2 in SSH exchanges and is not offering the newer ciphers.

I have this test code:

`use strict;
use warnings;
use Net::SSH2;

print "libssh2 version ", scalar &Net::SSH2::version, "\n";

my $host = "192.168.0.10";
my $port = 22;
my $user = 'test';
my $password = 'test';

my $ssh2 = Net::SSH2->new();

$ssh2->connect($host, $port) or die "Failed to connect";
$ssh2->auth(username => $user, password => $password, interact => 1) or die "Failed to auth";`

Which runs like this:

`C:\working-dir>sshtest.pl
libssh2 version 1.11.0
Failed to connect at C:\working-dir\sshtest.pl line 15.`

Note the available libssh2 version reported by Net::SSH2 is v1.11.0.

But the initial SSH packet exchange (obtained with Wireshark then follow TCP stream) shows:

`SSH-2.0-OpenSSH_8.8
**SSH-2.0-libssh2_1.8.2**
....
.O8.!."....."..h.....curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256....rsa-sha2-512,rsa-sha2-256...lchacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com...lchacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com...Tumac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com...Tumac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com....none,zlib@openssh.com....none,zlib@openssh.com...........................
**.......(.....i.+....~diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1....ssh-rsa,ssh-dss....aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,cast128-cbc,3des-cbc....aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,cast128-cbc,3des-cbc...qhmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com...qhmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com....none....none.............)...P<....**`

Note that Net::SSH2 sends SSH protocol version as SSH-2.0-libssh2_1.8.2

The SSH connection fails because Net::SSH2 is missing the required data encryption ciphers required by the test host.

Hopefully I'm not missing anything obvious..

Thanks

**Comment by PL-SalvadorFandino** [comment]
Net::SSH2 has not been updated to use any new functionality available from libssh2 1.11 yet.

But anyway, if the library reports it is using 1.8.2 it is because it is being compiled against that version of the library.

**Comment by rkitover** [comment]
It looks like you're on Windows, I believe Strawberry perl ships their own libssh2.

Try your experiment in WSL linux.

**Comment by lgastevens** [comment]
Got it working, with Strawberry Perl v5.32.1 MSWin32-x64-multi-thread!!
And I can confirm that Net::SSH2 v0.73 works fine with libssh2 v1.11.0 and I get all the latest ciphers with it, or at least the rsa-sha2-512 and rsa-sha2-256 ones which I was after.
There were a few reasons why it was not working for me initially.
Strawberry perl seems to rename the OpenSSL DLL like libcrypto-1_1-x64__.dll and libssl-1_1-x64__.dll, by adding a shlib_variant => "__" (which insert just before the .dll file prefix).
So when building OpenSSL, in order to then build libssh2, OpenSSL needs to create the same DLL files, otherwise when moving the libssh2.dll into Strawberry's c/bin directory, the dll won't be able to use the Strawberry OpenSSL DLLs...
Also wasted time as the libssh2 INSTALL_CMAKE.md install steps always end up producing libssh2.dll with Debug enabled, and this dll then only runs if it can find the vcruntime140d.dll & ucrtbased.dll which are only present if Microsoft Visual Studio is installed.. so the DLL is not portable to other Windows systems..  and the solution is "cmake --build . --config Release".

 I paste here below my notes, in case they come handy for someone else.

====

These steps used Strawberry Perl v5.32.1 built for MSWin32-x64-multi-thread

tee for windows was obtained here: https://code.google.com/archive/p/wintee/ 
 download wtee.exe and placed in C:\Windows\System32


==========================
INSTALLATION of OPENSSL
==========================

If already installed, delete:
C:\Program Files\OpenSSL
C:\Program Files\Common Files\SSL


Download OpenSSL from http://www.openssl.org
Unzip openssl-1.1.1u.tar.gz
CD into C:\Users\Ludovico\Downloads\openssl-1.1.1u
Read C:\Users\Ludovico\Downloads\openssl-1.1.1u\INSTALL
Read C:\Users\Ludovico\Downloads\openssl-1.1.1u\NOTES.WIN

Install NSAM from https://www.nasm.us
	run exe installer as Admin
	install for all users
	then add C:\Program Files\NASM to Path


C:\Users\Ludovico\Downloads\Updating NetSSH2 libssh2 - Jun2023>type 99__.conf
(
        "VC-WIN64A-ludo" => {
                inherit_from => [ 'VC-WIN64A' ],
                shlib_variant => "__",
        }
);


Copy file 99__.conf into:
C:\Users\Ludovico\Downloads\openssl-1.1.1u\Configurations


C:\Users\Ludovico>cd C:\Users\Ludovico\Downloads\openssl-1.1.1u
C:\Users\Ludovico\Downloads\openssl-1.1.1u>perl Configure VC-WIN64A-ludo
Configuring OpenSSL version 1.1.1u (0x1010115fL) for VC-WIN64A
Using os-specific seed configuration
Creating configdata.pm
Creating makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************

C:\Users\Ludovico\Downloads\openssl-1.1.1u>
C:\Users\Ludovico\Downloads\openssl-1.1.1u>mkdir logs


Download Microsoft Visual C compiler (Community edition) from https://visualstudio.microsoft.com/vs/features/cplusplus/
And Install it. (takes a while to install)

Then run Start / Visual Studio 2022 / x64 Native Tools Command Prompt for VS 2022

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'


C:\Program Files\Microsoft Visual Studio\2022\Community>cd C:\Users\Ludovico\Downloads\openssl-1.1.1u

C:\Users\Ludovico\Downloads\openssl-1.1.1u>nmake 2>&1 | wtee logs\nmake.out

C:\Users\Ludovico\Downloads\openssl-1.1.1u>nmake test 2>&1 | wtee logs\nmake_test.out


Run the same Start / Visual Studio 2022 / x64 Native Tools Command Prompt for VS 2022
  but as Administrator now
  

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>cd C:\Users\Ludovico\Downloads\openssl-1.1.1u

C:\Users\Ludovico\Downloads\openssl-1.1.1u>nmake install 2>&1 | wtee logs\nmake_install.out




==========================
INSTALLATION of LISSH2
==========================

Download libssh2 from http://www.libssh2.org
Unzip libssh2-1.11.0.tar.gz
CD into C:\Users\Ludovico\Downloads\libssh2-1.11.0

Read C:\Users\Ludovico\Downloads\libssh2-1.11.0\README
Read C:\Users\Ludovico\Downloads\libssh2-1.11.0\docs\INSTALL_CMAKE.md



Then run Start / Visual Studio 2022 / x64 Native Tools Command Prompt for VS 2022

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\2022\Community>cd C:\Users\Ludovico\Downloads\libssh2-1.11.0

C:\Users\Ludovico\Downloads\libssh2-1.11.0>
C:\Users\Ludovico\Downloads\libssh2-1.11.0>mkdir logs
C:\Users\Ludovico\Downloads\libssh2-1.11.0>mkdir dll

C:\Users\Ludovico\Downloads\libssh2-1.11.0>cd dll

C:\Users\Ludovico\Downloads\libssh2-1.11.0\dll>


C:\Users\Ludovico\Downloads\libssh2-1.11.0\dll>cmake -DCRYPTO_BACKEND=OpenSSL -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=.\dll .. 2>&1 | wtee ..\logs\cmake.out

C:\Users\Ludovico\Downloads\libssh2-1.11.0\dll>cmake --build . --config Release 2>&1 | wtee ..\logs\cmake_build.out


DLL is in:
C:\Users\Ludovico\Downloads\libssh2-1.11.0\dll\src\Release\libssh2.dll

Copy it to:
C:\Users\Ludovico\Downloads\Strawberry\replace\libssh2.dll

Then rename it to:
C:\Users\Ludovico\Downloads\Strawberry\replace\libssh2-1__.dll


Backup:
C:\Strawberry\c\bin\libssh2-1__.dll
To:
C:\Users\Ludovico\Downloads\Strawberry\backup\libssh2-1__.dll

Now copy:
C:\Users\Ludovico\Downloads\Strawberry\replace\libssh2-1__.dll
Into:
C:\Strawberry\c\bin\
1 DLL files should be replaced.





==========================
INSTALATION of Net::SSH2
==========================
Download Net-SSH2 from https://metacpan.org/pod/Net::SSH2
Unzip Net-SSH2-0.73.tar.gz
CD into C:\Users\Ludovico\Downloads\Net-SSH2-0.73

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>mkdir logs

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>perl Makefile.PL lib=C:\Users\Ludovico\Downloads\libssh2-1.11.0\dll inc=C:\Users\Ludovico\Downloads\libssh2-1.11.0\include ldargs="-lz" 2>&1 | wtee logs\perl_makefile.out

The libssh2 library is required by this module.  If you don't have it, you can
download it from http://www.libssh2.org; you may also need OpenSSL, which can
be obtained from http://www.openssl.org , or libgcrypt, which can be obtained
from http://www.gnupg.org .

Debian:   sudo aptitude install libssh2-1-dev
OpenSUSE: sudo zypper in libssh2-1 libssh2-devel

You can pass your libssh2 lib and include dirs (and extra link args) on the
command line. E.g.:

    perl Makefile.PL lib=$HOME/libssh2/lib inc=$HOME/libssh2/include \
        ldargs="-lz"

These can also be set through the LIBSSH2_LIB/LIBSSH2_INCLUDE/LIBSSH2_LDARGS
environment variables.

To build with libgcrypt instead of OpenSSL, use the crypto_backend
option when calling Makefile.PL, e.g.:

    perl Makefile.PL crypto_backend=gcrypt

Checking if your kit is complete...
Looks good
WARNING: Older versions of ExtUtils::MakeMaker may errantly install README.pod as part of this distribution. It is recommended to avoid using this path in
CPAN modules.
Generating a gmake-style Makefile
Writing Makefile for Net::SSH2
Writing MYMETA.yml and MYMETA.json

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>gmake 2>&1 | wtee logs\gmake.out

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>gmake test 2>&1 | wtee logs\gmake_test.out

C:\Users\Ludovico\Downloads\Net-SSH2-0.73>gmake install 2>&1 | wtee logs\gmake_install.out


The above installs Net::SS2 into Strawberry \perl\site\lib

But, Strawberry comes with Net::SSH2 already installed under \perl\vendor\lib:

C:\STRAWB~1\perl\vendor\lib\auto\Net\SSH2\SSH2.xs.dll
C:\STRAWB~1\perl\vendor\lib\Net\SSH2.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\Channel.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\Constants.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\Dir.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\File.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\KnownHosts.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\Listener.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\PublicKey.pm
C:\STRAWB~1\perl\vendor\lib\Net\SSH2\SFTP.pm

So manually delete these files/folders:

dir  C:\STRAWB~1\perl\vendor\lib\auto\Net\SSH2
file C:\STRAWB~1\perl\vendor\lib\Net\SSH2.pm
dir  C:\STRAWB~1\perl\vendor\lib\Net\SSH2

**Comment by lgastevens** [comment]
All good, already works!
