### ISSUE TITLE
Compression zlib can not be set

### ISSUE THREAD

**Issue by GwenDragon** [rkitover/net-ssh2#7]
Setting zlib compression client <-> server and vice versa does not work.

Try this snippet:

```perl
#!/usr/bin/perl
		
use strict;
use warnings;
		
use Net::SSH2; #
		
my $server   = 'myserver.org'; #change to your own server for your needs!
my $user     = 'meomy';
my $password = 'ThIsIsYuRpaZZwurd';
		
my $ssh2     = Net::SSH2->new();
$ssh2->connect($server, 22) or die $!;
		
$ssh2->auth_password($user,$password);
	
$ssh2->method('COMP_CS', 'zlib');
print "COMP_CS is ", $ssh2->method('COMP_CS');
$ssh2->method('COMP_SC', 'zlib');
print "COMP_SC is ", $ssh2->method('COMP_SC');
$ssh2->disconnect();

```

`ssh2->method('COMP_CS')` and  `ssh2->method('COMP_SC')` always shows _none_

Tested with Debian 6.06 / libssh2 1.4.2-1.1 / openssh 6.0p1-3

**Comment by jamessan** [comment]
libssh2 with compression fixes has been released and the net-ssh2 changes to support the compression API have been merged.  The compression support can be enabled as below

    my $ssh = Net::SSH2->new();
    $ssh->connect($host, $port, Compress => 1);
