### ISSUE TITLE
Expose libssh2_keepalive API

### ISSUE THREAD

**Issue by jamessan** [rkitover/net-ssh2#9]
In my environment, we do a lot of communication with hosts that may lose connectivity for various reasons.  Having access to the libssh2_keepalive API would make detecting and reacting to these situations a lot easier.

**Comment by jamessan** [comment]
@salva This can be closed now, right?  Looks like you pushed the keepalive changes some time ago.

**Comment by salva** [comment]
My last comment still applies. The keep alive implementation in libssh2 is half done and so buggy and can corrupt the session.

So, IIRC, the keep alive feature is wrapped in Net::SSH2, but using it is still a bad idea!

**Comment by jamessan** [comment]
That's fine.  The request was to have the functionality available, which it is.  I'll keep the risks in mind if/when I end up using it.
